remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  
include:
  - PRIVACY_POLICY.md
  - README.md
exclude:
  - "*"
